---
title: "labo1_loadRecord_Mark"
author: "Pol Renau Larrodé"
date: "13/9/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data
Data és  el document adult.data que es troba en el directori de treball. 
```{r}
df<-read.table("adult.data",header=F, sep=",", 
               fill=FALSE, strip.white=TRUE,na.string="?")

#aixó es pot fer en el read table, fent col.names = c("age",...,"salari")
names(df)<- c("age","type.employer","fnlwgt","education","education.num","marital",
              "ocupation","relationship","race","sex","capital.gain","capital.loss",
              "hours-per-week", "native-country","salari")

dim(df)
names(df)

summary(df)
```

## Sample  Selection
seleccionem una mostra de 5000 observacions aleatories.
```{r}

set.seed(14121997)
sam<-sample(1:nrow(df),5000)
#per veure la sintaxis ?nom_comanda a la consola

sam<- sort(sam)

# Mirem les dades ho comentem perque no volem basura al document
#attributes(df)
#o fer-ho amb
str(df)

#seleccionem el sample
df2<-df[sam,]


```

### Save sample binary files
```{r}

save(list="df2",file="mostra.RData")
```

